### ISSUE TITLE
Planteamiento

### ISSUE THREAD

**Issue by PriscillaCamposZamora** [PriscillaCamposZamora/Interfaces-Con-Perif-ricos#8]

**Comment by PriscillaCamposZamora** [comment]
Proyecto compartido en Overleaf para realizar el planteamiento de la solución [aquí](https://www.overleaf.com/read/qqyjdbpfxvrm#e5dc55)

**Comment by AnthonyAS15** [comment]
Planteamiento de las partes 2 y 3 realizado.

El planteamiento de la parte 1 se ha visto retrasado debido al estado de uno de los miembros del equipo.

**Comment by AnthonyAS15** [comment]
Se volvió a subir el documento con el planteamiento de la parte 1 añadido.
